export enum AuthErrorCode {
    INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',

    INVALID_ACCESS_TOKEN = 'AUTH_INVALID_ACCESS_TOKEN',

    INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',

    REFRESH_TOKEN_REUSED = 'AUTH_REFRESH_TOKEN_REUSED',

    SESSION_REVOKED = 'AUTH_SESSION_REVOKED',

    EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',

    INVALID_EMAIL_VERIFICATION_TOKEN =
        'AUTH_INVALID_EMAIL_VERIFICATION_TOKEN',

    INVALID_PASSWORD_RESET_TOKEN =
        'AUTH_INVALID_PASSWORD_RESET_TOKEN',
    
    AUTH_RATE_LIMITED = 'AUTH_RATE_LIMITED',
    AUTH_RATE_LIMITER_UNAVAILABLE = 'AUTH_RATE_LIMITER_UNAVAILABLE',
}